<?xml version="1.0" ?>
<robot name="Design" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--<xacro:include filename="$(find gripper_description)/urdf/materials.xacro" />-->

<!--<xacro:include filename="$(find gripper_description)/urdf/Design.gazebo" />-->

<xacro:include filename="$(find version1_description)/urdf/inertias.xacro" />

<xacro:property name="fingerForce" value = "0.0001"/>

<xacro:macro name="segment" params="name parent length">
	<xacro:seg name="${name}" length="${length}"/>
	<xacro:seg_joint seg1="${parent}" seg2="${name}" length="${length}"/>
	<xacro:seg_trans seg1="${parent}" seg2="${name}"/>
</xacro:macro>

<xacro:macro name="seg" params="name length">
	<link name="${name}">
		<visual>
			<geometry>
				<box size="0.02 0.02 ${length}"/>
			</geometry>
			<origin xyz="0 0 ${length/2}"/>
			<material name="white"/>
		</visual>
		<xacro:box_inertial_with_origin x="0.02" y="0.02" z="${length}" mass="0.01">
			<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
		</xacro:box_inertial_with_origin>
		<!--
		<inertial>
			<mass value="0.001"/>
			<inertia ixx="0.000000001" ixy="0.000000001" ixz="0.000000001" iyy="0.000000001" iyz="0.000000001" izz="0.000000001"/>
		</inertial> -->
		<collision>
			<geometry>
				<box size="0.02 0.02 ${length}"/>
			</geometry>
			<origin xyz="0 0 ${length/2}"/>
		</collision>
	</link>
	<gazebo reference="${name}">
		<mu1>0.2</mu1>
		<mu2>0.2</mu2>
		<selfCollide>true</selfCollide>
		<gravity>true</gravity>
	</gazebo>
</xacro:macro>


<xacro:macro name="seg_joint" params="seg1 seg2 length">
	<joint name="${seg1}_${seg2}_joint" type="revolute">
		<axis xyz="1 0 0"/>
		<limit effort="${fingerForce}" lower="-1" upper="1" velocity="1"/>
		<origin xyz="0 0 ${length}" rpy="0 0 0"/>
		<parent link="${seg1}"/>
		<child link="${seg2}"/>
	</joint>
</xacro:macro>


<xacro:macro name="seg_joint_offset" params="seg1 seg2 length offset rotation">
	<joint name="${seg1}_${seg2}_joint" type="revolute">
		<axis xyz="1 0 0"/>
		<limit effort="${fingerForce}" lower="-1" upper="1" velocity="1"/>
		<origin xyz="${offset}" rpy="${rotation}"/>
		<parent link="${seg1}"/>
		<child link="${seg2}"/>
	</joint>
</xacro:macro>

<xacro:macro name="seg_trans" params="seg1 seg2">
	<transmission name="${seg1}_${seg2}_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="${seg1}_${seg2}_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="${seg1}_${seg2}_joint">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
	</transmission>
	<gazebo reference="${seg1}_${seg2}_joint">
		<mu1 value="200.0"/>
		<mu2 value="100.0"/>
		<kp value = "10000000.0" />
		<kd value = "1.0" />
		<material>Gazebo/Grey</material>
	</gazebo>
</xacro:macro>


</robot>
