type: "effort_controllers/JointGroupPositionController"
publish_rate: 100
joints:
 - Rev1
 - Rev2
 - Rev3
 - Rev4

Rev1:
  pid: {p : 700.0, i : 30.0, d : 0.0}
Rev2:
  pid: {p : 1000.0, i : 10.0, d : 0.0, i_clamp_min : -1000, i_clamp_max : 1000}
Rev3:
  pid: {p : 700.0, i : 10.0, d : 0.0, i_clamp_min : -1000, i_clamp_max : 1000}
Rev4:
  pid: {p : 400.0, i : 10.0, d : 0.0, i_clamp_min : -1000, i_clamp_max : 1000}

