
type: "effort_controllers/JointGroupPositionController"
publish_rate: 100
joints:
 - Rev1
 - Rev2
 - Rev3
 - Rev4

Rev1:
  pid: {p : 5000.0, i : 30.0, d : 3.0}
Rev2:
  pid: {p : 6000.0, i : 10.0, d : 1.0, i_clamp_min : -1000, i_clamp_max : 1000}
Rev3:
  pid: {p : 5000.0, i : 10.0, d : 2.0, i_clamp_min : -1000, i_clamp_max : 1000}
Rev4:
  pid: {p : 5000.0, i : 10.0, d : 1.0, i_clamp_min : -1000, i_clamp_max : 1000}
